
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javie
 */
public class FramePrincipal extends javax.swing.JFrame {

    static Datos[] listaDatos = new Datos[5];
    Frame2 f2 = new Frame2();
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btt_Agregar = new javax.swing.JButton();
        txt_Monto = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttt_Frame2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        btt_Agregar.setText("Agregar");
        btt_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btt_Agregar);
        btt_Agregar.setBounds(100, 420, 140, 40);
        jPanel1.add(txt_Monto);
        txt_Monto.setBounds(100, 330, 280, 50);
        jPanel1.add(txt_Nombre);
        txt_Nombre.setBounds(100, 50, 280, 50);
        jPanel1.add(txt_Apellido);
        txt_Apellido.setBounds(100, 190, 280, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Monto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 280, 170, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 0, 170, 50);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 140, 170, 50);

        bttt_Frame2.setText("Frame2");
        bttt_Frame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttt_Frame2ActionPerformed(evt);
            }
        });
        jPanel1.add(bttt_Frame2);
        bttt_Frame2.setBounds(250, 420, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_AgregarActionPerformed
        
        boolean bandera = false;
        
        for (int i = 0; i < listaDatos.length; i++) {
            if (listaDatos[i] == null) {
                int monto = Integer.parseInt(txt_Monto.getText());
                Datos datito = new Datos(txt_Nombre.getText(), txt_Apellido.getText(), monto);
                listaDatos[i] = datito;
                bandera = true;
                break;
            }
        }
        
        if (!bandera) {
            JOptionPane.showMessageDialog(null, "Se llego al limite de los 5 usuarios");
        }
        
        for (int i = 0; i < listaDatos.length; i++) {
            if (listaDatos[i] != null) {
                System.out.println("Nombre: " + listaDatos[i].nombre + ", Apellido: " + listaDatos[i].apellido + ", Monto: " + String.valueOf(listaDatos[i].monto));
            }
        }
    }//GEN-LAST:event_btt_AgregarActionPerformed

    private void bttt_Frame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttt_Frame2ActionPerformed
        f2.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_bttt_Frame2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_Agregar;
    private javax.swing.JButton bttt_Frame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Monto;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
