/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javie
 */
public class Frame2 extends javax.swing.JFrame {
    
    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Indice = new javax.swing.JLabel();
        btt_VerDatos = new javax.swing.JButton();
        cbx_Nombres = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        lbl_Indice.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lbl_Indice.setText("Numero");
        jPanel1.add(lbl_Indice);
        lbl_Indice.setBounds(150, 220, 170, 50);

        btt_VerDatos.setText("Ver datos");
        btt_VerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_VerDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btt_VerDatos);
        btt_VerDatos.setBounds(10, 60, 120, 30);

        cbx_Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_NombresActionPerformed(evt);
            }
        });
        jPanel1.add(cbx_Nombres);
        cbx_Nombres.setBounds(10, 110, 280, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("Frame 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 170, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_VerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_VerDatosActionPerformed
        FramePrincipal fp = new FramePrincipal();
        cbx_Nombres.removeAllItems();
        
        Datos[] datosTemporales = fp.listaDatos;
        
        System.out.println("IMPRIMIENDO DESDE EL FRAME 2");
        for (int i = 0; i < datosTemporales.length; i++) {
            if (datosTemporales[i] != null) {
                System.out.println("Nombre: " + datosTemporales[i].nombre + ", Apellido: " + datosTemporales[i].apellido + ", Monto: " + String.valueOf(datosTemporales[i].monto));
            }
        }
        
        //fp.listaDatos[2] = new Datos("IPC1", "Laboratorio", 1000);
        for (int i = 0; i < datosTemporales.length; i++) {
            if (datosTemporales[i] != null) {
                cbx_Nombres.addItem(datosTemporales[i].nombre);
            }
        }        
    }//GEN-LAST:event_btt_VerDatosActionPerformed

    private void cbx_NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_NombresActionPerformed
        lbl_Indice.setText(String.valueOf(cbx_Nombres.getSelectedIndex()));
        
        int valorElegido = cbx_Nombres.getSelectedIndex();
        FramePrincipal pf = new FramePrincipal();
        
        System.out.println(pf.listaDatos[valorElegido].nombre);
    }//GEN-LAST:event_cbx_NombresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_VerDatos;
    private javax.swing.JComboBox<String> cbx_Nombres;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Indice;
    // End of variables declaration//GEN-END:variables
}
