
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javie
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    public static Cliente[] listaClientes = new Cliente[5];
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        initComponents2();
    }
    
    public void initComponents2() {
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btt_Agregar = new javax.swing.JButton();
        txt_Cui = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btt_Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("CUI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 90, 110, 40);

        btt_Agregar.setBackground(new java.awt.Color(255, 102, 102));
        btt_Agregar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btt_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        btt_Agregar.setText("Agregar");
        btt_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btt_Agregar);
        btt_Agregar.setBounds(340, 220, 280, 50);

        txt_Cui.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txt_Cui);
        txt_Cui.setBounds(20, 130, 280, 50);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Clase 5");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 160, 60);

        txt_Nombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txt_Nombre);
        txt_Nombre.setBounds(340, 130, 280, 50);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 90, 110, 40);

        txt_Apellido.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txt_Apellido);
        txt_Apellido.setBounds(20, 220, 280, 50);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 110, 40);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 760, 170);

        btt_Actualizar.setBackground(new java.awt.Color(255, 102, 102));
        btt_Actualizar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btt_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btt_Actualizar.setText("Refresh");
        btt_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btt_Actualizar);
        btt_Actualizar.setBounds(640, 220, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_AgregarActionPerformed
        
        Cliente nuevoCliente = new Cliente(Integer.parseInt(txt_Cui.getText()), txt_Nombre.getText(), txt_Apellido.getText());
        
        boolean bandera = false;
        for (int i = 0; i < listaClientes.length; i++) {
            if (listaClientes[i] == null) {
                listaClientes[i] = nuevoCliente;
                bandera = true;
                break;
            }
        }
        
        if (bandera == false) {
            System.out.println("SE LLEGO AL LIMITE DE USUARIOS");
            JOptionPane.showMessageDialog(null, "Se llego al limite de usuarios", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        
        for (int i = 0; i < listaClientes.length; i++) {
            if (listaClientes[i] != null) {
                listaClientes[i].Imprimir();
            }
        }
        
        txt_Cui.setText("");
        txt_Nombre.setText("");
        txt_Apellido.setText("");
    }//GEN-LAST:event_btt_AgregarActionPerformed

    private void btt_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_ActualizarActionPerformed
        for (int i = 0; i < listaClientes.length; i++) {
            if (listaClientes[i] != null) {
                listaClientes[i].Imprimir();
            }
        }
        
        String[][] matriz = new String[listaClientes.length][3];
        for (int i = 0; i < listaClientes.length; i++) {
            if (listaClientes[i] != null) {
                matriz[i][0] = String.valueOf(listaClientes[i].cui);
                matriz[i][1] = listaClientes[i].nombre;
                matriz[i][2] = listaClientes[i].apellido;
            }
        }
        
        String[] encabezado = {"CUI", "Nombre", "Apellido"};
        tablaDatos.setModel(new DefaultTableModel(
                matriz, 
                encabezado
        ));
        
    }//GEN-LAST:event_btt_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_Actualizar;
    private javax.swing.JButton btt_Agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Cui;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
