/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sanke;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

public class panel extends javax.swing.JFrame {

    ArrayList<String> historial = new ArrayList<>();
    //jlabel -> botones, txt
    JLabel[][] cuadriculaJuego;

    String direccion = "der";

    // hilos 
    private Thread hiloRepintar;

    //borde del tablero
    int izquierda = 0;
    int derecha = 10;

    //
    int x = 1;
    int y = 1;

    //posicion inical del snake
    int snakex = 5;
    int snakey = 5;

    //fruta
    int frutax = 1;
    int frutay = 1;

    // velocidad del sanke
    int velocidad = 1000;

    int contadorfrutas = 0;

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        snakeGame();
    }

    public void snakeGame() {

        // visibilidad del panel
        this.jPanel1.setVisible(true);

        //matriz del juego
        cuadriculaJuego = new JLabel[10][10];

        // un doble for para manejar la matriz
        for (int i = 0; i < cuadriculaJuego.length; i++) {
            for (int j = 0; j < cuadriculaJuego.length; j++) {

                //poder crear un label en esa poscion
                cuadriculaJuego[i][j] = new JLabel();
                cuadriculaJuego[i][j].setOpaque(true);

                cuadriculaJuego[i][j].setBackground(Color.white);

                // posicion x y posicion y
                // tamanio de cada cuadro
                cuadriculaJuego[i][j].setBounds(x, y, 50, 50);

                x = x + 51;
                this.jPanel1.add(cuadriculaJuego[i][j]);
            }
            y = y + 51;
            x = 1;
        }

        // pintar el snake
        cuadriculaJuego[snakex][snakey].setBackground(Color.red);

        // 1,1 de color verde
        cuadriculaJuego[frutax][frutay].setBackground(Color.green);

        //arranque del hilo
    }

    // funcion de mover el snake
    public void mover() {
        System.out.println("Aca si imprime");
            this.requestFocus(true);
            if (this.direccion.equals("arr")) {
                snakex--;
                //pintar
                cuadriculaJuego[snakex][snakey].setBackground(Color.red);
                //despintar
                cuadriculaJuego[snakex + 1][snakey].setBackground(Color.white);
            } else if (this.direccion.equals("aba")) {
                snakex++;
                //pintar
                cuadriculaJuego[snakex][snakey].setBackground(Color.red);
                //despintar
                cuadriculaJuego[snakex - 1][snakey].setBackground(Color.white);
            } else if (this.direccion.equals("der")) {
                snakey++;
                //pintar
                cuadriculaJuego[snakex][snakey].setBackground(Color.red);
                //despintar
                cuadriculaJuego[snakex][snakey - 1].setBackground(Color.white);
            } else if (this.direccion.equals("izq")) {
                snakey--;
                //pintar
                cuadriculaJuego[snakex][snakey].setBackground(Color.red);
                //despintar
                cuadriculaJuego[snakex][snakey + 1].setBackground(Color.white);
            }

            // if 
            // el movimiento del snake
            // if el boton derecha se prociono snakey --;
            // el boton de hacia arriba fue procionad snakex --;
            //otro if para el choque
//            if ( cuadriculaJuego[snakex][snakey] || || ||){
//                System.out.println("hubo un choque");
//            }
            //if contarfutas >0
            // velocidad = velocidad - 0.30
            // if cuadriculaJuego[snakex][snakey] == cuadriculaJuego[frutax][frutay]
            // cuadriculaJuego[frutax][frutay]. colro blanco
            //velocidad es una espera 
            try {
                Thread.sleep(velocidad);
            } catch (InterruptedException ex) {
                Logger.getLogger(panel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
    }

    public void actualizarIntervalo() {
        this.lbl_intervalo.setText(String.valueOf(velocidad));
        this.velocidad = this.velocidad - 50;
    }

    public void avanzar() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btt_Izquierda = new javax.swing.JButton();
        btt_Arriba = new javax.swing.JButton();
        btt_Abajo = new javax.swing.JButton();
        btt_Derecha = new javax.swing.JButton();
        btt_Historial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_intervalo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btt_Izquierda.setText("Izquierda");
        btt_Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_IzquierdaActionPerformed(evt);
            }
        });

        btt_Arriba.setText("Arriba");
        btt_Arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_ArribaActionPerformed(evt);
            }
        });

        btt_Abajo.setText("Abajo");
        btt_Abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_AbajoActionPerformed(evt);
            }
        });

        btt_Derecha.setText("Derecha");
        btt_Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_DerechaActionPerformed(evt);
            }
        });

        btt_Historial.setText("Historial");
        btt_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_HistorialActionPerformed(evt);
            }
        });

        jLabel1.setText("Intervalo");

        lbl_intervalo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_intervalo.setText("mostrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btt_Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btt_Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(btt_Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(btt_Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btt_Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbl_intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btt_Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btt_Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btt_Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btt_Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lbl_intervalo.getAccessibleContext().setAccessibleName("lbl_Intervalo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        hiloRepintar = new Thread(() -> {
            while(true) {
                this.mover();
                this.actualizarIntervalo();
            }
        });
        hiloRepintar.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("hola");
    }//GEN-LAST:event_formKeyPressed

    private void btt_ArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_ArribaActionPerformed
        this.requestFocus(true);
        this.direccion = "arr";
        historial.add("Preciono ARRIBA");
        //panel.cambiarDireccion("ar");
    }//GEN-LAST:event_btt_ArribaActionPerformed

    private void btt_AbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_AbajoActionPerformed
        this.requestFocus(true);
        historial.add("Preciono ABAJO");
        this.direccion = "aba";
    }//GEN-LAST:event_btt_AbajoActionPerformed

    private void btt_DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_DerechaActionPerformed
        this.requestFocus(true);
        historial.add("Preciono DERECHA");
        this.direccion = "der";
    }//GEN-LAST:event_btt_DerechaActionPerformed

    private void btt_IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_IzquierdaActionPerformed
        this.requestFocus(true);
        historial.add("Preciono IZQUIERDA");
        this.direccion = "izq";
    }//GEN-LAST:event_btt_IzquierdaActionPerformed

    private void btt_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_HistorialActionPerformed
        for (String cadena : historial) {
            System.out.println(cadena);
        }
    }//GEN-LAST:event_btt_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new panel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_Abajo;
    private javax.swing.JButton btt_Arriba;
    private javax.swing.JButton btt_Derecha;
    private javax.swing.JButton btt_Historial;
    private javax.swing.JButton btt_Izquierda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_intervalo;
    // End of variables declaration//GEN-END:variables
}
